### ISSUE TITLE
example_mass_spring_qp.m only works with slack bounds equal to -1

### ISSUE THREAD

**Issue by lenvm** [giaf/hpipm#101]
I have tried to use a slack variable in example **example_mass_spring_qp.m**

Please find my code [here](https://github.com/lenvm/hpipm/blob/ocp_qp_withslack/examples/matlab_octave/example_mass_spring_qp_withslack.m).

Only when I set the lower slack bounds associated to the lower and upper constrains to a value between -1.000000001 and -0.999999999 in [line 175](https://github.com/lenvm/hpipm/blob/ocp_qp_withslack/examples/matlab_octave/example_mass_spring_qp_withslack.m#L175), I manage to get the solver to finish with status 0. Any other value I tried results in a failed solution.

I would like to be able to use 0 as a slack bound.

Could you please have a look what causes the solver to not find a solution with lower slack bounds equal to 0?

**Comment by giaf** [comment]
The example seemed to have a number of issues that are not representative of usual soft constraints usage, e.g. having no penalty on the slacks and attempting to soften the initial state.
Closing now as likely not relevant any more.

**Comment by lenvm** [comment]
Actually I’d still be interested to be able to use lower slack bounds associated to the lower and upper constraints with a value different than -1. Could you perhaps provide a minimum working example that uses a lower slack bound of 0?
