### ISSUE TITLE
Bug in Python Interface of getting solution

### ISSUE THREAD

**Issue by reichardtj** [giaf/hpipm#108]
The code for getting a section of the solution contains a bug that shows up once one tries to get the solution for an `idx_start` > 0 and `idx_end != None`. See https://github.com/giaf/hpipm/blob/e2d25a28c2b9fbaaf7a1b38cd15c5a35b09f82d8/interfaces/python/hpipm_python/hpipm_python/wrapper/hpipm_ocp_qp_sol.py#L89-L96

`u` is initialized as empty list but is then indexed into with index `i` running from `idx_start` to `idx_end` and that breaks if `idx_start` > 0 since only `u[0]` exists.

The quickfix would be to simply put the data into `u[-1]` instead of `u[i]`, but I'll try to make a PR with a bit more comprehensive refactoring and remove the code duplication.

**Comment by giaf** [comment]
Ok after merging, I notice that using python 3.8 on `example_qp_getting_started.py` I get the warning
```
/home/gianluca/.local/lib/python3.8/site-packages/hpipm_python/wrapper/hpipm_ocp_qp_sol.py:110: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(var).T
```
Since you look much more skilled than me on pyhton, how should this be fixed properly? :p
Thanks!

**Comment by reichardtj** [comment]
ups - the varying dimensions .... the quick fix would be `return np.array(var, dtype=object).T` which would return an np.array  of np.arrays if the dimensions differ per stage or a matrix of type object if they don't. The old version returned an np.array if only one index was queried and a list of arrays when a range was requested. 
`return var if len(var) > 1 else np.array(var).T` would reestablish this. Which do you prefer?

**Comment by giaf** [comment]
I would go for the proposal keeping the same functionality as the old version, i.e one np.array if only one index is queried and a list of arrays when a range is requested. This for consistency with other parts of the interface as it currently is.

**Comment by giaf** [comment]
Ah don't worry about the qcqp, I can quickly fix myself once we are good with the qp

**Comment by reichardtj** [comment]
I reestablished the old return behavior In PR#110, there should be no warning anymore. Python examples run without.

**Comment by reichardtj** [comment]
closed with https://github.com/giaf/hpipm/pull/110
