### ISSUE TITLE
Some d_ocp_qp functions possibly broken in latest versions

### ISSUE THREAD

**Issue by gerkone** [giaf/hpipm#111]
Some of the `d_ocp_qp` functions might be broken/work differently after the last commits.
I do not know what could be the problem (maybe the constraint are evaluated differently?), or what exactly are the interested functions, but I think the breaking commit could be d08380ea955c68462c185d6434af174199a5fa75. I did not investigate further.

The solver is used in other projects, most notably @alexliniger 's [MPCC](https://github.com/alexliniger/MPCC). With a fresh install (cloning the latest version from the repos) the visible result is that the solver almost always returns 0.
Thanks

**Comment by giaf** [comment]
Hi Gianluca,

thanks for the bug report.
In theory that commit is just performing some code editing that should not change functionality at all.
Could you double-check that the issue is indeed appearing because of that commit?
And could you give me some more information about what the issue is? Wrong solution? Solver not converging?
Thanks!

**Comment by giaf** [comment]
Ok I think I found the issue, it should be fixed now with this commit https://github.com/giaf/hpipm/commit/651b126441ea88b707b7351b8f23bf2f96486072
Could you check that everything works fine again?

**Comment by gerkone** [comment]
Hey, thanks for the quick response.
Commit 651b126441ea88b707b7351b8f23bf2f96486072 seems to have indeed solved it. Thanks!
Just for future reference (and if it's easy to explain), what was going wrong?

Thank you again for your support, and also for your library

**Comment by giaf** [comment]
In the old version, there were some VECCP (copy vector) outside the loop that were copying some vectors for all constraints stages, and then in the loop the softed constraints were updated properly.
In the new version, the VECCP were removed and the loop was only computing properly in case of soft constraints, while hard ones were not computed at all.
Now the `else` conditions is also processing properly in case of hard constraints.

**Comment by gerkone** [comment]
Perfect. I initially said that it was the constraints because in the MPCC they were ignored, and the supposedly breaking commit only changed the constraints components.
Thanks again
