### ISSUE TITLE
how to set inital guess for ocp_qp in  C interface?

### ISSUE THREAD

**Issue by Mesywang** [giaf/hpipm#113]
Hi Gianluca, thanks for maintaining this project!
I didn't find a example which is setting inital guess in ocp_qp c examples, i try `d_ocp_qp_sol_set()` to set initial guess, but it 
didn't seem to work, Can you give me a simple example? Thanks a lot for any help!

**Comment by giaf** [comment]
Thanks!
Yes you can use `d_ocp_qp_sol_set()` and then tell the solver to use warm starting setting this option https://github.com/giaf/hpipm/blob/master/include/hpipm_d_ocp_qp_ipm.h#L76

**Comment by Mesywang** [comment]
Thanks!
