### ISSUE TITLE
Irritating nans printed in every iteration

### ISSUE THREAD

**Issue by reichardtj** [giaf/hpipm#118]
It appears this line
https://github.com/giaf/hpipm/blob/bd0a9b666720139c771c05a9f8b44a1346ab02ec/ocp_qp/x_ocp_qp_ipm.c#L2664
is a leftover from a recent fix but it prints an irritating single line with every call to the solver.

I suppose it can be removed without harm. Pls. confirm.

**Comment by giaf** [comment]
Yes you are right, thanks for noticing!
