### ISSUE TITLE
How To Print The Cost of Objective Function

### ISSUE THREAD

**Issue by Mesywang** [giaf/hpipm#121]
Hi Gianluca, thanks for maintaining this project!
I want to ask how to print the cost of objective function after convergence? Thanks a lot for any help!

**Comment by giaf** [comment]
Hi, thanks for the interest in HPIPM!
At the moment this option is not implemented, but it can be added if needed.

**Comment by Mesywang** [comment]
thanks for your reply!
I design an iterative optimization problem and each sub-problem is ocp-qp, i am solving it using hpipm, now i want to know if my iterative optimization problem is convergent, and i need get the cost of each sub-problem, so can you provide this interface for me? thanks for your help!

**Comment by giaf** [comment]
Sorry for the delay, I finally had the chance to implement it (only for the OCP QP solver for now).
You can give a try as here https://github.com/giaf/hpipm/blob/master/test_problems/test_d_ocp.c#L1248

**Comment by Mesywang** [comment]
Perfect！Thanks for your help!

**Comment by giaf** [comment]
It is now implemented for all solvers for all QPs.
