### ISSUE TITLE
stat_m outputs description

### ISSUE THREAD

**Issue by a1gituser** [giaf/hpipm#126]
Hello

is there any description of what the different outputs in stat_m are, and/or how they're computed?
specifically what is the difference between the residuals named "lin res" and the ones just called "res", for example "lin res stat" and "res stat".

thanks!

**Comment by giaf** [comment]
The residuals named simply `res` are the ones that refer to the residuals of the current QP solution at each IPM iteration.
So they are the residuals in evaluating the (nonlinear) KKT optimality conditions.
When they are small enough, it means the IPM algorithm found an accurate enough solution to the QP problem.

The residuals named `lin res` refer to the residuals in computing the solution of the linearized KKT system at each IPM iteration.
They are a measure of the numerical accuracy in solving this linear system for obtaining the current search direction step.
In the basic IPM algorithm these residuals are not computed; they are only if the iterative refinement option is enabled.
In this case, a few iterative refinement steps are performed in an attempt to improve the accuracy in the solution of the KKT system, in case the `lin res` show that is not accurate enough.
