### ISSUE TITLE
help setting hidxe

### ISSUE THREAD

**Issue by a1gituser** [giaf/hpipm#130]
Hello,

I'm trying to setup a problem where I have no box constraints for states or inputs, except for the initial condition constraint for the states. There are some general constraints, but I don't think they any effect on what I need to know. I am trying to understand how to setup hidxe: If nu=1, and nx=3 for all stages, then for the first stage should hidxe be set to {0,1,2}?

The reason I'm asking is because I'm setting hidxe[0] = {0,1,2}... but when I use `d_ocp_qp_codegen` it is printing hidxe[0] = {0,0,1}, and I don't understand why internally HPIPM is changing the values, or if I have something wrong in the setup.

thanks

**Comment by a1gituser** [comment]
resolved it my self. thanks

**Comment by giaf** [comment]
Sorry it fell of my radar somehow.
It should have been hidxe[0]={1,2,3} as variables are ordered inputs first and states after.
Otherwise set hidxbxe as {0,1,2} as this targets only the states.

What was the issue for you at the end?
