### ISSUE TITLE
Be sure to specify the initial value of the local variable.

### ISSUE THREAD

**Issue by HuNingHe** [giaf/hpipm#131]
- I have two identical codes that work fine on ubuntu 20.04 but get a sigsegv error on ubuntu 22.04. 
- Through debugging, it was found that the local variable "ii" in line 49 of the [aux_mem.cc ](https://github.com/giaf/hpipm/blob/master/auxiliary/aux_mem.c) file was randomly initialized to a large value, because it was not specified as 0.
- The initial guess was that it was caused by the different default behavior of the compiler, and it should be much better if it was specified as 0

**Comment by giaf** [comment]
Thanks a lot for the detailed bug report!
It is now fixed here https://github.com/giaf/hpipm/commit/425e5962fd3a17d8db9481890212d9c391e95826
