### ISSUE TITLE
Cannot make hpipm in container, errors with BLASFEO

### ISSUE THREAD

**Issue by jkaob** [giaf/hpipm#132]
Hi,

I am having issues with the installation of HPIPM 0.1.3 , using docker. Blasfeo 0.1.3 is successfully installed in /opt/blasfeo/, but the `make` step of the installation is not working:
```
git clone https://github.com/giaf/hpipm.git
cd hpipm/
git checkout tags/0.1.3
mkdir -p build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release 
make -j8
```

This gives me (many) errors such as
```
/root/.../hpipm/cond/x_part_cond_qcqp.c: In function ‘d_part_cond_qcqp_expand_sol’:
/root/.../hpipm/cond/x_part_cond_qcqp.c:750:70: error: incompatible type for argument 3 of ‘blasfeo_dsymv_l’
                            SYMV_L(nu[jj]+nx[jj], nu[jj]+nx[jj], 1.0, ocp_qp->Hq[jj]+kk, 0, 0, ocp_qp_sol->ux+jj, 0, 0.0, part_cond_ws->cond_ws[ii].tmp_nuxM, 0, part_cond_ws->cond_ws[ii].tmp_nuxM, 0);
...
...
/root/.../hpipm/cond/d_cond_aux.c:77:16: error: too many arguments to function ‘blasfeo_dsymv_l’
   77 | #define SYMV_L blasfeo_dsymv_l

```

What can be the cause of this? I am trying to use Hpipm with the `ct-optcon` library.
I have tried various build flags

Thanks for the help.

**UPDATE:**  
It seems that the error is with versions of blasfeo and hpipm `0.1.3`, as the latest commits both build!

**Comment by giaf** [comment]
The signature of the symv_l routine has been changed at some point, it may be that the version 0.1.3 of BLASFEO and 0.1.3 of HPIPM are not taken at the same time and so use different signatures.

As you said, the latest versions of BLASFEO and HPIPM both use the last signature.
