### ISSUE TITLE
Make error for examples/c/example_d_ocp_qp.c

### ISSUE THREAD

**Issue by iMax4** [giaf/hpipm#169]
The build has worked for me so far without any problems, but since yesterday I get the following error:

![Bildschirmfoto 2024-08-21 um 19 13 37](https://github.com/user-attachments/assets/ce054cbc-90a0-4877-9614-ce1006993c17)

**Comment by giaf** [comment]
This should fix the issue https://github.com/giaf/hpipm/commit/a4bb6749969fd6aa417781a8c35d9a01563200ab

**Comment by iMax4** [comment]
Yes, it works again. Thanks!
