### ISSUE TITLE
Error in building hpipm

### ISSUE THREAD

**Issue by prajwalthakur** [giaf/hpipm#172]
hi everyone. I am getting an error while building the hpipm 
I followed the steps mentioned 
1. `RUN git clone https://github.com/giaf/blasfeo.git && cd blasfeo && make shared_library -j 4 && sudo make install_shared`
2. `RUN git clone https://github.com/giaf/h ,  any help is appreciated . (Getting error in the second step .)
![image](https://github.com/user-attachments/assets/cfa812ab-67ff-493f-911b-9e677a805426)

**Comment by giaf** [comment]
Sorry forgot to include the header files in the last commit, done now here https://github.com/giaf/hpipm/commit/6a0267dca70d6377859efc82dca8a5a1c509c2ae
Thanks for reporting
