### ISSUE TITLE
Linker errors when building an executable for Intel Core target with hpipm + blasfeo

### ISSUE THREAD

**Issue by mkatliar** [giaf/hpipm#46]
I have an exectuable which links to hpipm and blasfeo. 
* I built and installed blasfeo with `TARGET = X64_INTEL_CORE`. 
* Then I build and install hpipm with `TARGET = SSE3` and `BLASFEO_PATH` set to where my blasfeo is installed. 
* Then I build an executable which links to both blasfeo and hpipm, and I get the following linker errors:
```
[build] [ 96%] Linking CXX executable ../../bin/soft_constraints
[build] /opt/hpipm/lib/libhpipm.a(d_ocp_qp_ipm.o): In function `d_solve_ocp_qp_ipm':
[build] d_ocp_qp_ipm.c:(.text+0x1764): undefined reference to `d_backup_res_m'
[build] d_ocp_qp_ipm.c:(.text+0x1e16): undefined reference to `d_compute_alpha_qp'
[build] d_ocp_qp_ipm.c:(.text+0x1e58): undefined reference to `d_update_var_qp'
[build] d_ocp_qp_ipm.c:(.text+0x1e77): undefined reference to `d_backup_res_m'
[build] d_ocp_qp_ipm.c:(.text+0x2014): undefined reference to `d_update_var_qp'
...
```
If I build blasfeo with `TARGET = AVX`, the executable links fine, but I get SIGILL when running it because apparently hpipm tries to execute an instruction not supported by my CPU, and this is not what I want.

**Comment by giaf** [comment]
Hey, there is no `SSE3` target in HPIPM, the only two valid options are the ones listed in Makefile.rule in HPIPM: `AVX` and `GENERIC`.

In HPIPM, all linear algebra comes form BLASFEO, and the HPIPM has only a minor effect on performance (all operations with linear complexity on the number of stage variables).

**Comment by giaf** [comment]
@mkatliar is this solving?

**Comment by giaf** [comment]
Thanks for the suggestion!
