### ISSUE TITLE
Matlab-Python interface

### ISSUE THREAD

**Issue by alexliniger** [giaf/hpipm#47]
The Matlab interface reads the A and B matrices incorrectly, and transposing the matrices solves the issue.

I also have an improved getting_started.m script if you are interested.

**Comment by zanellia** [comment]
@giaf I cannot have a look before October 2. Did we break anything while introducing the latest changes? :P

**Comment by aliniger** [comment]
@zanellia the interface works you just defined a system which is not controllable A = [1, 0; 1, 1], B = [0;1], the first state does just stay where it is. But your example still works because internally you transpose it somewhere, which makes it into a discrete time double integrator.

**Comment by giaf** [comment]
@zanellia I'm having a look at it now, it looks like the issue boils down to the fact that python assumes row-major, again :p

**Comment by giaf** [comment]
@alexliniger this should fix it.

I'm curious about your improved getting_started.m : what is it in there? The current one is kind on identical in python, matlab and octave, and wants to show what are the available features.
