### ISSUE TITLE
stable branch: Make test_problems

### ISSUE THREAD

**Issue by oguzhancebe** [giaf/hpipm#59]
Hello,
First, thank you very much for the library. I had the following issue in stable branch:

make static_library worked, but make test_problem results in the following error for me

`gcc -o test.out d_tools.o test_d_ocp.o -L. libhpipm.a  /opt/blasfeo/lib/libblasfeo.a -lm  #-pg
libhpipm.a(d_ocp_qp_ipm.o): In function `d_solve_ocp_qp_ipm':
d_ocp_qp_ipm.c:(.text+0x11da): undefined reference to `dvecnrm_inf_libstr'
d_ocp_qp_ipm.c:(.text+0x1205): undefined reference to `dvecnrm_inf_libstr'
d_ocp_qp_ipm.c:(.text+0x1233): undefined reference to `dvecnrm_inf_libstr'
d_ocp_qp_ipm.c:(.text+0x1261): undefined reference to `dvecnrm_inf_libstr'
d_ocp_qp_ipm.c:(.text+0x133b): undefined reference to `dvecnrm_inf_libstr'
libhpipm.a(d_ocp_qp_ipm.o):d_ocp_qp_ipm.c:(.text+0x1354): more undefined references to `dvecnrm_inf_libstr' follow
libhpipm.a(d_ocp_qp_kkt.o): In function `d_compute_res_ocp_qp':
d_ocp_qp_kkt.c:(.text+0x126a): undefined reference to `dgemv_diag_libstr'
collect2: error: ld returned 1 exit status
Makefile:74: recipe for target 'obj' failed
`
I don't have the same problem for ct-v2 branch, but I would like to try the tree-structured quadratic program solver. What would you recommend for me?
Best regards

**Comment by giaf** [comment]
Hi, first of all thank you for your interest in HPIPM.

The missing files are in an old version of BLASFEO, and they have been renamed or removed in more recent versions.

I would suggest you to use the `master` branch from both HPIPM and BLASFEO, since these are always kept syncronized.
