### ISSUE TITLE
Python example fails due to recent contribution (new exception)

### ISSUE THREAD

**Issue by pepperpo** [giaf/hpipm#63]
getting_started.py fails at line 66
`qp.set('A', [A, A, A, A, A])`
Due to a recent modification to the ...wrapper/hpipm_ocp_qp.py at line 176:
raise Exception("Trying to assign value which is not a vector nor a scalar. Exiting.")

Is it enough to do?
`qp.set('A', np.array([A, A, A, A, A]))`

**Comment by zanellia** [comment]
hey @pepperpo, it should be fixed now, thanks for the heads up ;)
