### ISSUE TITLE
Is it possible to make shared_library in win10 powershell?

### ISSUE THREAD

**Issue by YouShaoze** [giaf/hpipm#74]
Hey~, I want to use tihs code in matlab 2016b on win10, but it has a problem:

E:\EnZone\Desktop\MPCC\Matlab\hpipm\blasfeo> make shared_library -j4
Parsing Makefile.rule
process_begin: CreateProcess(NULL, uname -s, ...) failed.
make: Makefile.rule:119: pipe: No error
process_begin: CreateProcess(NULL, ulimit -s, ...) failed.
make: Makefile.rule:321: pipe: No such file or directory
'bc' is not an internal or external command, nor is it a runnable program or batch file. 
touch ./include/blasfeo_target.h
process_begin: CreateProcess(NULL, touch ./include/blasfeo_target.h, ...) failed.
make (e=2): The specified file could not be found by the system。
make: *** [Makefile:865: target] Error 2

so I want to know  Whether it need to be based on the linux system to run perfectly ??
And I'm a  novice , I only want to I just want to see the results of the experiment https://github.com/alexliniger/MPCC.

**Comment by giaf** [comment]
Hi, the make build system is not supposed to work on the PowerShell in windows 10.
You could give a try with the windows subsystem for linux (WSL) https://docs.microsoft.com/en-us/windows/wsl/install-win10 but I never did myself, so I can not guarantee that it works there.

What surely works is to use matlab from a linux distribution like Ubuntu, as the make build system has been designed for it.

**Comment by giaf** [comment]
Otherwise you can use the CMake build system to build shared libraries for both HPIPM and BLASFEO in windows, this may just be what you need.

**Comment by YouShaoze** [comment]
> Otherwise you can use the CMake build system to build shared libraries for both HPIPM and BLASFEO in windows, this may just be what you need.

Thank you for your help : )
