### ISSUE TITLE
Clarify licenses

### ISSUE THREAD

**Issue by eric-heiden** [giaf/hpipm#78]
Thank you so much for providing this awesome library!

I noticed some inconsistencies in the licenses of some files. Most of them are 2-Clause BSD, but in the following files you include the GPL license:
- CMakeLists.txt
- Files in `archive/`
- Files in `examples/c/`
- Files in `test_problems/`
- Files in `interfaces/archive/octave/`

Could you consider unifying the license terms of those files, so that it will be easier for others to use your library in non-GPL code?

One last thing: the file [experimental/andrea/notes/syscop.bib](https://github.com/giaf/hpipm/blob/master/experimental/andrea/notes/syscop.bib) is an external symbolic link that cannot be resolved.

**Comment by giaf** [comment]
First of all, thanks for the interest in HPIPM!

The license has been changed to BSD-2 rather recently, thanks for pointing out that some files still need to be updated!

The `syscop.bib` is an internal bib file we use at our lab. In general please disregard the content of the `experimental` and `archive` folders, there is a lot of junk there.
I will upload in these days a link to a new reference about HPIPM, so stay tuned :)

**Comment by eric-heiden** [comment]
Thanks a lot, this will be helpful! For now, we can simply exclude the few files that do not use the BSD-2 license yet.

**Comment by eric-heiden** [comment]
Thanks a lot for your fast fixes!
However, a few files still have the GPL-3 license instead of BSD-2:
- hpipm/examples/c/data/getting_started_data.c
- hpipm/test_problems/pendulum/vde_hess_model.c
- hpipm/test_problems/pendulum/ode_model.c
- hpipm/test_problems/pendulum/vde_adj_model.c
- hpipm/test_problems/pendulum/jac_model.c
- hpipm/test_problems/pendulum/vde_forw_model.c

**Comment by giaf** [comment]
These are fixed too now. Thanks for spotting them.

There is now a new reference in the readme file with a recent paper specifically about HPIPM.

**Comment by eric-heiden** [comment]
Thank you very much, they are all fixed now!
I will check out your paper.
