### ISSUE TITLE
mexa64 file for dense qp in MATLAB

### ISSUE THREAD

**Issue by Endro-tech** [giaf/hpipm#86]
Hello @giaf 

I would like to use the dense QP solver in the MATLAB environment. I could find the mexa64 files for the OCP QP, but not for the dense QP.  
As I have no experience in C, I was wondering if the generation of these mexa files is easy, and in case it is, I would like to ask if you planned to provide it?

Looking forward for an answer and best regards.

**Comment by giaf** [comment]
Hi there,

I just added a basic matlab/octave interface for the dense QP https://github.com/giaf/hpipm/commit/266048467167dfce697a3eebe1f19691cc109cc6
Here is an example https://github.com/giaf/hpipm/blob/master/examples/matlab_octave/example_getting_started_dense_qp.m

Some features like codegen data or load from data are not supported, as they will require quite a bit more work in the C code too.

Hope it helps!

**Comment by Endro-tech** [comment]
Thanks a lot!
