### ISSUE TITLE
Building on Arm Cortex-A57: Unrecognized command line option -mavx

### ISSUE THREAD

**Issue by aungriah** [giaf/hpipm#91]
Hello, I am trying to build this on a Jetson TX2 (Arm Cortex-A57), so I have defined the TARGET accordingly in the Makefile.rule file in the blasefeo root folder. When following your instructions (specifically running make static_library from the hpipm root folder), an error is returned indicating "the command line option -mavx is not found".
Do you know what could be the issue?

**Comment by giaf** [comment]
Hi! Just switch to the `GENERIC` target in HPIPM
https://github.com/giaf/hpipm/blob/master/Makefile.rule#L53
the default value is `AVX` which is an instruction set of the x86 architecture not supported in ARM.
