### ISSUE TITLE
Not able to obtain lambda values

### ISSUE THREAD

**Issue by steradiant** [giaf/hpipm#92]
Hello,
I want to use the HPIPM as QP solver for a SQP-Algorithm. Therefore, I need to obtain the lambda (and possibly pi) values which result from the solution of the QP. How can I obtain these values? I'm using MATLAB and tried the straightforward approach sol.get('lambda'); but that didn't work.

**Comment by giaf** [comment]
Hi, that is not yet implemented in the matlab interface
https://github.com/giaf/hpipm/blob/master/interfaces/matlab_octave/ocp_qp_sol_get.c
I should have some time to look into it at the end of next week.

**Comment by steradiant** [comment]
Thanks! Is it implemented in another interface? I'm anyway considering on switching to C, also of speed considerations of function evaluations and so on.

**Comment by giaf** [comment]
With this commit I implemented the getting of the Lagrange multipliers for inequality (https://github.com/giaf/hpipm/commit/006ed06e8151254138a75e9b60af65d78d226fc9) and dynamics (https://github.com/giaf/hpipm/commit/f257970f544bba270404599d570d24056ce23522) for the OCP QP solver.
I also updated the `example_getting_started.m` to show how to use them.
